In [1]:
import pandas as pd
import numpy as np
from os.path import join
import os
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

## 1. Extracting all Uniprot ID - RHEA reaction ID pairs from the downloaded file from UniProt:

In [77]:
df_uniprot = pd.read_excel(join("..", "..", "old_data", "Uniprot", "uniprot-reviewed yes_transport.xlsx"))
df_uniprot = df_uniprot.dropna(
    subset=['Gene ontology (molecular function)'])
df_uniprot

,Entry,Catalytic activity,Gene ontology (molecular function)
0,B4ELA5,CATALYTIC ACTIVITY: Reaction=a purine D-ribonu...,guanosine phosphorylase activity [GO:0047975];...
1,P07465,NaN,copper ion binding [GO:0005507]; electron tran...
2,Q88YN8,CATALYTIC ACTIVITY: Reaction=H2O + phosphonoac...,magnesium ion binding [GO:0000287]; phosphonoa...
3,P20235,CATALYTIC ACTIVITY: Reaction=a ribonucleoside ...,RNA-directed 5'-3' RNA polymerase activity [GO...
4,A5FEA5,CATALYTIC ACTIVITY: Reaction=[protein]-L-isoas...,protein-L-isoaspartate (D-aspartate) O-methylt...
...,...,...,...
567478,A6TAW7,CATALYTIC ACTIVITY: Reaction=3 H(+)(out) + 2 N...,sodium:proton antiporter activity [GO:0015385]
567479,B0BZW3,CATALYTIC ACTIVITY: Reaction=a plastoquinone +...,"4 iron, 4 sulfur cluster binding [GO:0051539];..."
567480,Q6GB05,CATALYTIC ACTIVITY: Reaction=H2O + 3 O2 + 3 pr...,nitronate monooxygenase activity [GO:0018580];...
567481,Q5RBF2,CATALYTIC ACTIVITY: Reaction=S-ubiquitinyl-[E2...,ubiquitin protein ligase activity [GO:0061630]
567482,A8GHW9,CATALYTIC ACTIVITY: Reaction=a 2'-deoxyribonuc...,ATP binding [GO:0005524]; metal ion binding [G...

In [76]:
df_uniprot_new = pd.read_excel(
    join("..", "..", "data", "Uniprot", "uniprot-reviewed yes_transport.xlsx"))
df_uniprot_new = df_uniprot_new.drop(columns=['From'])
df_uniprot_new = df_uniprot_new.rename(
        columns={'Gene Ontology (molecular function)': 'Gene ontology (molecular function)'})
df_uniprot_new = df_uniprot_new.dropna(subset=['Gene ontology (molecular function)'])
df_uniprot_new

,Entry,Catalytic activity,Gene ontology (molecular function)
0,Q9HVR6,CATALYTIC ACTIVITY: Reaction=a dipeptide(out) ...,ATP binding [GO:0005524]; ATP hydrolysis activ...
1,Q9HTR3,NaN,amine transmembrane transporter activity [GO:0...
2,Q5W7C1,NaN,UDP-glucose transmembrane transporter activity...
3,Q07824,NaN,antiporter activity [GO:0015297]; spermidine t...
4,Q8UWF0,NaN,choline transmembrane transporter activity [GO...
...,...,...,...
3667,P36372,CATALYTIC ACTIVITY: Reaction=a peptide antigen...,ABC-type peptide antigen transporter activity ...
3668,M9PEI8,NaN,ceramide binding [GO:0097001]; ceramide transf...
3669,O94639,NaN,high-affinity zinc transmembrane transporter a...
3670,Q8R4T9,CATALYTIC ACTIVITY: [Isoform A1]: Reaction=ure...,cell adhesion molecule binding [GO:0050839]; u...
3671,Q8I298,NaN,phosphatidylcholine transporter activity [GO:0...

In [78]:
df_uniprot = pd.concat([df_uniprot, df_uniprot_new])

In [81]:
df_uniprot = df_uniprot.drop_duplicates(subset=['Entry'])
df_uniprot

,Entry,Catalytic activity,Gene ontology (molecular function)
0,B4ELA5,CATALYTIC ACTIVITY: Reaction=a purine D-ribonu...,guanosine phosphorylase activity [GO:0047975];...
1,P07465,NaN,copper ion binding [GO:0005507]; electron tran...
2,Q88YN8,CATALYTIC ACTIVITY: Reaction=H2O + phosphonoac...,magnesium ion binding [GO:0000287]; phosphonoa...
3,P20235,CATALYTIC ACTIVITY: Reaction=a ribonucleoside ...,RNA-directed 5'-3' RNA polymerase activity [GO...
4,A5FEA5,CATALYTIC ACTIVITY: Reaction=[protein]-L-isoas...,protein-L-isoaspartate (D-aspartate) O-methylt...
...,...,...,...
3664,G5EB18,NaN,high-affinity secondary active nitrite transme...
3665,A0A9K3Y745,NaN,ABC-type oligopeptide transporter activity [GO...
3666,Q9DDS6,CATALYTIC ACTIVITY: Reaction=3 Na(+)(out) + ph...,sodium:inorganic phosphate symporter activity ...
3668,M9PEI8,NaN,ceramide binding [GO:0097001]; ceramide transf...
3671,Q8I298,NaN,phosphatidylcholine transporter activity [GO:0...

In [83]:
df_uniprot_new.to_csv('/data_link/servilla/SPOT2/data/output_new.tsv',
                  sep='\t', index=False)

In [67]:
start_rhea = "Xref=Rhea:"

def get_reaction_info(activity):
    reaction = activity.split(";")[0]
    reaction = reaction.replace("Reaction=", "")
    
    start_pos = activity.find(start_rhea)
    if start_pos != -1:
        rhea_ID = activity[start_pos + len(start_rhea):]
        rhea_ID = rhea_ID.split(",")[0]
    else:
        rhea_ID = np.nan
        
    return(rhea_ID, reaction)


def get_activtities(activities):
    activities = activities.split("CATALYTIC ACTIVITY: ")
    return(activities[1:])

In [ ]:
# df_reactions = pd.DataFrame(columns = ["Uniprot ID", "Reaction", "RHEA ID", "GO"])

# for ind in df_uniprot.index:
#     if ind % 1000 ==0:
#         print(ind)
#     activities = df_uniprot["Catalytic activity"][ind]
#     if not pd.isnull(activities):
#         activities = get_activtities(activities = activities)
#         for activity in activities:
#             if "(out)" in activity and "(in)" in activity:
#                 rhea_ID, reaction = get_reaction_info(activity)
#                 df_reactions = df_reactions.append({"Uniprot ID" : df_uniprot["Entry"][ind],
#                                                     "Reaction" : reaction, 
#                                                     "RHEA ID" : rhea_ID,
#                                                    "GO" : df_uniprot["Gene ontology (molecular function)"][ind]
#                                                    },
#                                                    ignore_index=True)
                
                
                
# print("Number of different UniProt IDs : %s \n\
# Number of different RHEA reaction IDs: %s" % (len(set(list(df_reactions["Uniprot ID"]))), len(set(list(df_reactions["RHEA ID"])))))                

# df_reactions

In [87]:
"""Below code to correct append error"""
df_uniprot = pd.read_csv('/data_link/servilla/SPOT2/data/output.tsv', sep='\t')
df_reactions = pd.DataFrame(
    columns=["Uniprot ID", "Reaction", "RHEA ID", "GO"])
rows = []  # Initialize an empty list to collect rows

for ind in df_uniprot.index:
    # if ind % 1000 == 0:
        # print(ind)
    activities = df_uniprot["Catalytic activity"][ind]
    if not pd.isnull(activities):
        activities = get_activtities(activities=activities)
        for activity in activities:
            if "(out)" in activity and "(in)" in activity:
                rhea_ID, reaction = get_reaction_info(activity)
                rows.append({
                    "Uniprot ID": df_uniprot["Entry"][ind],
                    "Reaction": reaction,
                    "RHEA ID": rhea_ID,
                    "GO": df_uniprot["Gene ontology (molecular function)"][ind]
                })

# Convert the list of rows to a DataFrame
df_new_rows = pd.DataFrame(rows)

# Concatenate the new rows DataFrame to the existing DataFrame
df_reactions = pd.concat([df_reactions, df_new_rows], ignore_index=True)

print("Number of different UniProt IDs : %s \n\
Number of different RHEA reaction IDs: %s" % (len(set(list(df_reactions["Uniprot ID"]))), len(set(list(df_reactions["RHEA ID"])))))

df_reactions

Number of different UniProt IDs : 13802
Number of different RHEA reaction IDs: 497

,Uniprot ID,Reaction,RHEA ID,GO
0,P63361,ATP + H2O + phosphate(out) = ADP + H(+) + 2 ph...,RHEA:24440,ATPase-coupled phosphate ion transmembrane tra...
1,Q5LBQ4,ATP + H2O + phosphate(out) = ADP + H(+) + 2 ph...,RHEA:24440,ATPase-coupled phosphate ion transmembrane tra...
2,P0AAH2,ATP + H2O + phosphate(out) = ADP + H(+) + 2 ph...,RHEA:24440,ATPase-coupled phosphate ion transmembrane tra...
3,Q3JTS8,ATP + H2O + phosphate(out) = ADP + H(+) + 2 ph...,RHEA:24440,ATPase-coupled phosphate ion transmembrane tra...
4,Q7U6R4,ATP + H2O + phosphate(out) = ADP + H(+) + 2 ph...,RHEA:24440,ATPase-coupled phosphate ion transmembrane tra...
...,...,...,...,...
17509,F1QRW4,"a 1,2-diacyl-sn-glycero-3-phosphocholine(in) =...",RHEA:38571,phosphatidylcholine binding [GO:0031210]; phos...
17510,F1QRW4,an N-(acyl)-sphingosylphosphocholine(in) = an ...,RHEA:43776,phosphatidylcholine binding [GO:0031210]; phos...
17511,A0A0H2ZLL3,ATP + ergothioneine(out) + H2O = ADP + ergothi...,RHEA:76247,ATP binding [GO:0005524]; ATP hydrolysis activ...
17512,B7CED8,ATP + Ca(2+)(in) + H2O = ADP + Ca(2+)(out) + H...,RHEA:18105,ATP binding [GO:0005524]; ATP hydrolysis activ...
17513,Q9DDS6,3 Na(+)(out) + phosphate(out) = 3 Na(+)(in) + ...,RHEA:71255,sodium:inorganic phosphate symporter activity ...

### 2. Mapping RHEA reaction IDs to substrate IDs:

### (a) Mapping RHEA reaction IDs to transported substrates:

In [88]:
def extract_RHEA_ID_and_CHEBI_IDs(entry):
    RHEA_ID = entry[0][len("ENTRY"): -1]
    RHEA_ID = RHEA_ID.split(" ")[-1]
    CHEBI_IDs = entry[2][len("EQUATION"): -1]
    CHEBI_IDs = CHEBI_IDs[CHEBI_IDs.index("CHEBI"):]
    
    sub_names = entry[1][len("DEFINITION"): -1]
    while sub_names[0] == " ":
        sub_names = sub_names[1:]
    
    return(RHEA_ID, CHEBI_IDs, sub_names)

def get_substrate_IDs(IDs):
    IDs = IDs.split(" = ")[0]
    IDs = IDs.split(" => ")[0]
    IDs = IDs.split(" <=> ")[0]
    IDs = IDs.replace(" + ", ";")
    IDs = IDs.split(";")
    return([ID.split(" ")[-1] for ID in IDs])

def get_substrate_names(names):
    names = names.split(" = ")[0]
    names = names.split(" => ")[0]
    names = names.split(" <=> ")[0]
    names = names.replace(" + ", ";")
    names = names.split(";")
    return([ID.split(" ")[-1] for ID in names])

def get_acess_array(names):
    []

In [93]:
df_RHEA = pd.DataFrame(columns = ["RHEA ID", "CHEBI_ID_list"])

# file1 = open(join("..", "..", "data", "reactions", "rhea-reactions.txt"), 'r')
# Lines = file1.readlines()

entry = ['ENTRY       RHEA:10192\n',
 'DEFINITION  ATP + H2O + sulfate(out) = ADP + H(+) + phosphate + sulfate(in)\n',
 'EQUATION    CHEBI:30616 + CHEBI:15377 + CHEBI:16189 = CHEBI:456216 + CHEBI:15378 + CHEBI:43474 + CHEBI:16189\n',
 'ENZYME      7.3.2.3\n',
 '///\n']

In [96]:
# Initialize an empty DataFrame
df_RHEA = pd.DataFrame(columns=["RHEA ID", "CHEBI_ID_list"])
rows = []  # Initialize an empty list to collect rows

# File path
file_path = join("..", "..", "data", "reactions", "rhea-reactions.txt")

# Read the file
with open(file_path, 'r') as file:
    Lines = file.readlines()

# Function to extract RHEA ID and CHEBI IDs


def extract_RHEA_ID_and_CHEBI_IDs(entry):
    rhea_id = None
    chebi_ids = []
    for line in entry:
        if line.startswith('ENTRY'):
            rhea_id = line.split()[1]
        elif line.startswith('EQUATION'):
            chebi_ids = [part.strip() for part in line.split()[1].split('+')]
    return rhea_id, chebi_ids


# Parse the file
start = 0
while start < len(Lines):
    try:
        end = Lines.index('///\n', start)
        entry = Lines[start:end]
        RHEA_ID, CHEBI_IDs = extract_RHEA_ID_and_CHEBI_IDs(entry)
        if RHEA_ID and CHEBI_IDs:
            rows.append({"RHEA ID": RHEA_ID, "CHEBI_ID_list": CHEBI_IDs})
        start = end + 1
    except ValueError:
        break

# Convert the list of rows to a DataFrame
df_new_rows = pd.DataFrame(rows)

# Concatenate the new rows DataFrame to the existing DataFrame
df_RHEA = pd.concat([df_RHEA, df_new_rows], ignore_index=True)

df_RHEA["RHEA ID"] = [float(ID.split(":")[-1]) for ID in df_RHEA["RHEA ID"]]
df_RHEA.to_pickle(
    join("..", "..", "data", "reactions", "RHEA_reaction_df.pkl"))
df_RHEA

# Display the DataFrame
print(df_RHEA)

       RHEA ID   CHEBI_ID_list
0      10000.0   [CHEBI:15377]
1      10001.0   [CHEBI:15377]
2      10002.0   [CHEBI:28938]
3      10003.0   [CHEBI:15377]
4      10004.0   [CHEBI:17484]
...        ...             ...
66431  79146.0   [CHEBI:33384]
66432  79155.0  [CHEBI:229705]
66433  79156.0  [CHEBI:229705]
66434  79157.0  [CHEBI:229705]
66435  79158.0  [CHEBI:229705]

[66436 rows x 2 columns]

In [ ]:
# df_RHEA = pd.DataFrame(columns = ["RHEA ID", "CHEBI_ID_list"])

# file1 = open(join("..", "..", "data", "reactions", "rhea-reactions.txt"), 'r')
# Lines = file1.readlines()

# while True:
#     try:
#         end = Lines.index('///\n')
#         entry = Lines[:end]
#         RHEA_ID, CHEBI_IDs, sub_names = extract_RHEA_ID_and_CHEBI_IDs(entry)
#         CHEBI_ID_list, sub_name_list = get_substrate_IDs(IDs = CHEBI_IDs), get_substrate_names(names = sub_names)
#         access_array = [True if "(out)" in sub or "(in)" in sub else False for sub in sub_name_list ]
#         CHEBI_ID_list = list(np.array(CHEBI_ID_list)[access_array])
#         Lines = Lines[end+1:]
#         df_RHEA = df_RHEA.append({"RHEA ID" : RHEA_ID, "CHEBI_ID_list" : CHEBI_ID_list}, ignore_index = True)
#     except ValueError:
#         break
        
# df_RHEA["RHEA ID"] = [float(ID.split(":")[-1]) for ID in df_RHEA["RHEA ID"]]
# df_RHEA.to_pickle(join("..", "..", "data", "reactions", "RHEA_reaction_df.pkl"))
# df_RHEA

In [98]:
def get_CHEBI_IDs_from_RHEA_ID(rhea_ID):
    rhea_ID = float(rhea_ID.replace("RHEA:", ""))
    try:
        CHEBI_IDs = list(df_RHEA["CHEBI_ID_list"].loc[df_RHEA["RHEA ID"] == rhea_ID])[0]
    except IndexError:
        CHEBI_IDs = []
    return(CHEBI_IDs)

In [ ]:
# df_prot_sub = pd.DataFrame(columns = ["Uniprot ID", "CHEBI ID"])

# for ind in df_reactions.index:
#     rhea_ID = df_reactions["RHEA ID"][ind]
#     if not pd.isnull(rhea_ID):
#         CHEBI_IDs = get_CHEBI_IDs_from_RHEA_ID(rhea_ID = rhea_ID)
#         UID = df_reactions["Uniprot ID"][ind]
#         for CHEBI_ID in CHEBI_IDs:
#             df_prot_sub = df_prot_sub.append({"Uniprot ID" : UID, "CHEBI ID" : CHEBI_ID}, ignore_index=True)
# df_prot_sub.drop_duplicates(inplace = True)
# df_prot_sub

In [99]:
'''Below code to correct append error'''


df_prot_sub = pd.DataFrame(columns=["Uniprot ID", "CHEBI ID"])
rows = []  # Initialize an empty list to collect rows

for ind in df_reactions.index:
    rhea_ID = df_reactions["RHEA ID"][ind]
    if not pd.isnull(rhea_ID):
        CHEBI_IDs = get_CHEBI_IDs_from_RHEA_ID(rhea_ID=rhea_ID)
        UID = df_reactions["Uniprot ID"][ind]
        for CHEBI_ID in CHEBI_IDs:
            rows.append({"Uniprot ID": UID, "CHEBI ID": CHEBI_ID})

# Convert the list of rows to a DataFrame
df_new_rows = pd.DataFrame(rows)

# Concatenate the new rows DataFrame to the existing DataFrame
df_prot_sub = pd.concat([df_prot_sub, df_new_rows], ignore_index=True)

df_prot_sub.drop_duplicates(inplace=True)
df_prot_sub

       Uniprot ID     CHEBI ID
0          P63361  CHEBI:30616
1          Q5LBQ4  CHEBI:30616
2          P0AAH2  CHEBI:30616
3          Q3JTS8  CHEBI:30616
4          Q7U6R4  CHEBI:30616
...           ...          ...
17509      F1QRW4  CHEBI:57643
17510      F1QRW4  CHEBI:64583
17511  A0A0H2ZLL3  CHEBI:30616
17512      B7CED8  CHEBI:30616
17513      Q9DDS6            3

[15007 rows x 2 columns]

In [100]:
df_prot_sub.rename(columns = {"CHEBI ID" : "molecule ID"}, inplace = True)

In [105]:
# Creating a copy with only the 'Uniprot ID' column
df_prot_sub_txt = df_prot_sub[['Uniprot ID']].copy()

df_prot_sub_txt.to_csv(join("..", "..", "data", "Uniprot",
                   "UNIPROT_IDs.txt"), sep="\t", index=False, header=False)

## 3. Downloading sequences via the UniProt mapping service (https://www.uniprot.org/uploadlists/):

In [106]:
Uniprot_IDs = list(set(df_prot_sub["Uniprot ID"]))

f = open(join("..", "..", "data", "Uniprot", "UNIPROT_IDs.txt"),"w")
for ID in list(set(Uniprot_IDs)):
    f.write(str(ID) + "\n")
f.close()

In [108]:
UNIPROT_df = pd.read_csv(join("..", "..", "data", "Uniprot", "UNIPROT_results.csv"), sep = "\t")
UNIPROT_df

      Uniprot ID   Entry                                           Sequence
0         Q1CR30  Q1CR30  MVVELKNIEKIYENGFHALKGVNLELKKGDILGVIGYSGAGKSTLI...
1         Q2A1I2  Q2A1I2  MSTGKIIQVIGAVIDVEFARDNTPKVYDALNVVEAGLVLEVQQQIG...
2         O67337  O67337  MGVKKLSRKDYLNILESILFIDFLKGLSVTLKNLLRRPITTEYPKE...
3         B1MPH4  B1MPH4  MNPDNYLYLAALIFTIGAAGVMLRRNAIVVFMSVELMLNAANLAFV...
4         Q6HP89  Q6HP89  MISFNNVSKVYESGGQSVHAVEDVTLSVEKGEIFGIIGFSGAGKST...
...          ...     ...                                                ...
13797     Q2GBB8  Q2GBB8  MPSISHPPSALRDFLRSEAAGGVILMAVAVLAMIVANSPLADSYFH...
13798     Q32DQ8  Q32DQ8  MTLKELLVGFGTQVRSIWMIGLHAFAKRETRMYPEEPVYLPPRYRG...
13799     B0BRX2  B0BRX2  MATGKIVQIIGAVIDVEFPQDAVPKVYDALKVESGLTLEVQQQLGG...
13800     Q9TDR1  Q9TDR1  MNPFASLTLTTLIILTIPIMMSNSNIYKTNLYPNYVKTTVSYAFTL...
13801     P29654  P29654  FWFFGHPEVYILILPGFGMISHIVAYYAGKKEPFGYMGMVWAMMAI...

[13802 rows x 3 columns]

In [109]:
df_prot_sub = df_prot_sub.merge(UNIPROT_df, on = "Uniprot ID", how = "left")
df_prot_sub

,Uniprot ID,molecule ID,Entry,Sequence
0,P63361,CHEBI:30616,P63361,MNLMAERSLENAVGEKMNATASSIKMRGEKVCVFYGEKQALFDVDL...
1,Q5LBQ4,CHEBI:30616,Q5LBQ4,MDTTVKIDARDVNFWYGDFHALKGISMEIEEKSVVAFIGPSGCGKS...
2,P0AAH2,CHEBI:30616,P0AAH2,MSMVETAPSKIQVRNLNFYYGKFHALKNINLDIAKNQVTAFIGPSG...
3,Q3JTS8,CHEBI:30616,Q3JTS8,MNMAESHLDPSKLATGPAGFGAAAGQRPLAPLNAKIEVKNLNFFYN...
4,Q7U6R4,CHEBI:30616,Q7U6R4,MTTSQLQTEQHQVSDDTAISIQNVTISYGSYEAVKNVYCDVPRGKV...
...,...,...,...,...
15002,F1QRW4,CHEBI:57643,F1QRW4,MVLIKEYRVVLPCSVEEYQVGQLFSVAEASKNETGGGEGIEVLKNE...
15003,F1QRW4,CHEBI:64583,F1QRW4,MVLIKEYRVVLPCSVEEYQVGQLFSVAEASKNETGGGEGIEVLKNE...
15004,A0A0H2ZLL3,CHEBI:30616,A0A0H2ZLL3,MIEYKNVALRYTEKDVLRDVNLQIEDGEFMVLVGPSGSGKTTMLKM...
15005,B7CED8,CHEBI:30616,B7CED8,MPEYGASLEELRALMEYRSAEAKEKIETDYGGTTGLCERLKTDPNN...
15006,Q9DDS6,3,Q9DDS6,MAPLAETHPASPPPELGADADKHEPQTPTRTLSPWPAQQWEPEQEE...

In [110]:
df_prot_sub.to_pickle(join("..", "..", "data", "Uniprot", "Transporter_Uniprot.pkl"))

In [111]:
df = pd.read_pickle(join("..", "..", "data", "Uniprot", "Transporter_Uniprot.pkl"))
df.to_csv(join("..", "..", "data", "Uniprot", "Transporter_Uniprot.csv"), index=False)